### ISSUE TITLE
开luci编译后生成的固件系统启动10秒左右后会重启

### ISSUE THREAD

**Issue by MarsHo1970** [wireless-tag-com/openwrt-ssd20x#1]
开luci编译后生成的固件，烧入成功后，系统启动10秒左右后会重启

**Comment by alan-wt** [comment]
因为原厂给的wifi驱动是ko编译死的，开启luci之后，会改变内核配置，导致skbuff变了。
如果需要使用luci，请先去掉wifi驱动

**Comment by luofuchong** [comment]
难怪，能把内核搞死，我也觉得是wifi驱动的问题(可是没看到驱动打印的异常信息)
