### ISSUE TITLE
使用设备树声明gpio和leds失败

### ISSUE THREAD

**Issue by styfstr** [wireless-tag-com/openwrt-ssd20x#2]
WT2022.dts内容如下：
![image](https://user-images.githubusercontent.com/44523785/115987946-ed2c5280-a5e9-11eb-8f4d-f7304213854e.png)

内核打印如下：
![image](https://user-images.githubusercontent.com/44523785/115987961-03d2a980-a5ea-11eb-83ad-807b5f9f0488.png)

没有leds相关打印

**Comment by alan-wt** [comment]
请参考WT2022-padmux-display.dtsi, 目前GPIO0-GPIO3都已经被内核其他模块（sdmmc和i2c1）使用了。
<PAD_GPIO0             PINMUX_FOR_GPIO_MODE      MDRV_PUSE_SDIO0_PWR >,
<PAD_GPIO1          PINMUX_FOR_GPIO_MODE        MDRV_PUSE_I2C1_DEV_RESET >,
<PAD_GPIO2          PINMUX_FOR_I2C1_MODE_1      MDRV_PUSE_I2C1_SCL >,
<PAD_GPIO3          PINMUX_FOR_I2C1_MODE_1      MDRV_PUSE_I2C1_SDA >,
请使用其他的GPIO

**Comment by styfstr** [comment]
这是我的pad配置，GPIO0-GPIO3并没有被占用。
![image](https://user-images.githubusercontent.com/44523785/116365809-35d94b00-a838-11eb-81cb-9e15c3c012e2.png)

**Comment by styfstr** [comment]
昨天按照你们要求，我又换了几个gpio测试了一下，/sys/class/ledes下依然是空的

**Comment by alan-wt** [comment]
WT2022-dispaly.dtsi里面使用：
goodix_rst = <PAD_GPIO1>;
            /*
             * padmux: 1 -> PAD_GPIO2, PAD_GPIO3
             *         2 -> PAD_HDMITX_SCL, PAD_HDMITX_SDA
             *         4 -> PAD_TTL22, PAD_TTL23
             *         5 -> PAD_SD_CLK, PAD_SD_CMD
            */
            i2c-padmux = <1>;
GPIO1-3是不能用的

**Comment by styfstr** [comment]
gpio0，gpio10，gpio12测试也是不可以的

**Comment by alan-wt** [comment]
led的定义
    gpio-leds {
        compatible = "gpio-leds";

        status {
            label = "led:status";
            gpios = <&gpio 10 1>;
        };
    };

**Comment by alan-wt** [comment]
你的dts中，这个是有问题，这个和gpiochip冲突了，不是这样定义的：
![image](https://user-images.githubusercontent.com/68888713/117939165-64781b00-b33a-11eb-8867-d7a7d1aa3842.png)

**Comment by styfstr** [comment]
感谢您的回复。
我按照上边指出的错误，重新修改设备树文件，问题依然没有解决，/sys/class/leds/ 里面仍然为空。下边是我的设备树配置：
![image](https://user-images.githubusercontent.com/44523785/117942265-760ef200-b33d-11eb-8044-eab94a73a71d.png)
